server:
  port: 5000
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  application:
    name: polling-api
  flyway:
    enable: true
    location: classpath:/db/migration
jwt:
  key:
    private: app.key
    public: app.pub
